# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [29]:
print(np.__version__)
np.__config__.show()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MKK1111999/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/MKK1111999/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MKK1111999/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117

#### 3. Create a null vector of size 10 (★☆☆)

In [30]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [31]:
Z = np.zeros((10,10))
print("%d bytes"%(Z.size*Z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [32]:
# python -c "import numpy as np; np.info(numpy.add)"

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [33]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [34]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [35]:
arr = np.arange(10,50)
arr = arr[::-1]
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [36]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [37]:
arr = np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [38]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [39]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.75716861 0.54100872 0.9283358 ]
  [0.70128978 0.44961885 0.42183863]
  [0.84967764 0.97394197 0.92289182]]

 [[0.87657632 0.31295557 0.34939942]
  [0.39492891 0.12646928 0.86291664]
  [0.69872427 0.41575601 0.34931622]]

 [[0.84380079 0.89916305 0.31653583]
  [0.16799286 0.55167718 0.07168409]
  [0.81535943 0.95360829 0.45925451]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [40]:
arr = np.random.random((10,10))
arr_min,arr_max = arr.min(),arr.max()
print(arr_min,arr_max)

0.0023784129261386067 0.960725394294661


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [41]:
arr = np.random.random(30)
print(arr.mean())

0.5798421445139551


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [42]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [43]:
arr = np.ones((5,5))
arr = np.pad(arr,pad_width =1,mode = 'constant',constant_values = 0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [44]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [45]:
arr = np.diag(1+np.arange(4),k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [46]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [47]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [48]:
arr = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [49]:
arr = np.random.random((5,5))
arr = (arr-arr.mean())/(arr.std())
print(arr)

[[ 1.22283571  0.62585371 -0.12963675 -1.23963679  1.20836588]
 [-1.02275589 -1.12782434  1.38917672  1.02116559 -0.58679669]
 [ 1.29632682 -0.88061563 -1.51802313  1.27689754 -1.40690087]
 [ 0.83658894 -0.0624077  -0.90660758 -0.78505275  0.16120109]
 [-0.0887313  -1.48270817  0.91412157  0.47160803  0.81355601]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [50]:
arr = np.dtype([("r",np.ubyte,1),
               ("g",np.ubyte,1),
               ("b",np.ubyte,1),
               ("a",np.ubyte,1)])
print(arr)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-50-fffd26271fdb>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  arr = np.dtype([("r",np.ubyte,1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [51]:
arr = np.dot(np.ones((5,3)),np.ones((3,2)))
print(arr)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [52]:
arr = np.arange(11)
arr[(3<arr) & (arr<=8)]*=-1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [60]:
from numpy import *
print(sum(range(5),-1))
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [61]:
Z=np.arange(3,4)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[3]
[27]
[4]
[False]
[0.+3.j]
[3.]
[False]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [62]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-62-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-62-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [63]:
arr= np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(arr)),arr))

[ -6. -10.  -5.  -2.  -6.  10.   7.   5.   6.  -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [64]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
print(np.intersect1d(arr1,arr2))

[1 3 4 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [65]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0
    print(Z)

[inf]
[inf]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [66]:
print( np.sqrt(-1))

nan


<ipython-input-66-609404d822cc>:1: RuntimeWarning: invalid value encountered in sqrt
  print( np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [67]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(np.datetime64('today', 'D'))
print(np.timedelta64(1, 'D'))

2020-08-04
2020-08-05
1 days


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [68]:
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [69]:
A=np.ones(3)*1
B=np.random.rand(3)*2
np.multiply(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[-0.29959102 -0.78684762 -0.68839684]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [70]:
Z= np.random.uniform(0,10,10)
print(np.trunc(Z))
print(Z-Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))

[3. 7. 2. 8. 6. 6. 2. 5. 6. 4.]
[3. 7. 2. 8. 6. 6. 2. 5. 6. 4.]
[3. 7. 2. 8. 6. 6. 2. 5. 6. 4.]
[3. 7. 2. 8. 6. 6. 2. 5. 6. 4.]
[3 7 2 8 6 6 2 5 6 4]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [71]:
arr = np.zeros((5,5))
arr+=np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [72]:
def generator():
    for x in range(10):
        yield x
Z = np.fromiter(generator(),dtype = int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [73]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [74]:
arr = np.random.random(10)
arr.sort()
print(arr)

[0.08029199 0.13453969 0.15675797 0.25634864 0.36648358 0.37895554
 0.39536882 0.61984838 0.65254615 0.65791002]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [75]:
arr = np.random.random(10)
print(np.add.reduce(arr))

3.8513608692288495


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [76]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
print(np.allclose(A,B))
print(np.array_equal(A,B))

[0 1 1 1 1]
[0 0 1 1 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [78]:
arr = np.zeros(10)
arr.flags.writeable = False
# arr[0]=1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [79]:
arr = np.random.random((10,2))
x,y = arr[:,0],arr[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.96774586 0.66629495 0.56963974 1.15127774 0.30829134 1.22372394
 0.62151319 0.30029918 0.74991472 0.44578531]
[0.55279951 1.41332945 1.46827812 0.91524338 0.59502997 0.8756069
 1.38591985 1.22253454 1.56813149 1.46036926]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [80]:
arr = np.random.random(10)
print(arr.argmax())
arr_max = arr.max()
index = np.where(arr==arr_max)
arr[index]=0
print(arr)

6
[0.42060907 0.71009747 0.85234046 0.59868426 0.24336287 0.75307884
 0.         0.26783162 0.80855367 0.84631313]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [81]:
Z = np.zeros((5,5), [('x',float),('y',float)])

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [82]:
x=np.arange(8)
print(x)
y=x+0.5
print(y)
c = 1.0/np.subtract.outer(x,y)
print(c)
print(np.linalg.det(c))

[0 1 2 3 4 5 6 7]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


In [83]:
import numpy as np

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [84]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).max)
    print(np.iinfo(dtype).min)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).eps)

127
-128
2147483647
-2147483648
9223372036854775807
-9223372036854775808
3.4028235e+38
-3.4028235e+38
1.1920929e-07
1.7976931348623157e+308
-1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [85]:
np.set_printoptions()
Z=np.zeros((10,10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [86]:
arr = np.arange(100)
value = np.random.uniform(0,100)
index = (np.abs(arr-value)).argmin()
print(arr[index])

3


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [87]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-87-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [88]:
# Z = np.random.random((10,2))
# X,Y = np.atleast_2d(Z[:,0], Z[:,1])
# D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
# print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.33943445 0.60178531 0.55864246 0.641299   0.46492835
  0.51637226 0.61890934 0.89408869 0.75183964]
 [0.33943445 0.         0.28653648 0.52960394 0.77820335 0.5347772
  0.43607607 0.29767822 0.58914855 0.53352426]
 [0.60178531 0.28653648 0.         0.51540353 0.84688374 0.60036056
  0.41037444 0.02575676 0.30263223 0.32248448]
 [0.55864246 0.52960394 0.51540353 0.         0.35229817 0.15920635
  0.10591735 0.54077492 0.65056314 0.36902887]
 [0.641299   0.77820335 0.84688374 0.35229817 0.         0.25043074
  0.445485   0.87264035 1.00279049 0.71679644]
 [0.46492835 0.5347772  0.60036056 0.15920635 0.25043074 0.
  0.21729648 0.62606485 0.78229445 0.51642101]
 [0.51637226 0.43607607 0.41037444 0.10591735 0.445485   0.21729648
  0.         0.43586729 0.56546416 0.3036645 ]
 [0.61890934 0.29767822 0.02575676 0.54077492 0.87264035 0.62606485
  0.43586729 0.         0.29379123 0.33772104]
 [0.89408869 0.58914855 0.30263223 0.65056314 1.00279049 0.78229445
  0.56546416 0.293791

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [89]:
arr = np.arange(10,dtype = np.float32)
arr = arr.astype(np.int32,copy =False)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [90]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n
            """)
arr_of_strings = np.genfromtxt(s,delimiter=",",dtype=np.int)
print(arr_of_strings)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [91]:
arr = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(arr):      #method1
    print(index,value)
for index in np.ndindex(arr.shape):         #method2
    print(index,arr[index])
for index in range(len(arr)):               #method3
    for j in range(len(arr[index])):
        print((index,j),arr[index][j])
for index,value in enumerate(arr):         #method4
    for val in enumerate(value):
        print((index,val[:][0]),val[:][1])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [92]:
x,y = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
d = np.sqrt(x**2+y**2)
mu,sigma = 0.0,1.0
G = np.exp(-((d-mu)**2)/(2*sigma**2))
print(G)

[[1.         0.96923323 0.8824969  0.7548396  0.60653066]
 [0.96923323 0.93941306 0.85534533 0.73161563 0.58786967]
 [0.8824969  0.85534533 0.77880078 0.66614361 0.53526143]
 [0.7548396  0.73161563 0.66614361 0.56978282 0.45783336]
 [0.60653066 0.58786967 0.53526143 0.45783336 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [93]:
n=5
p=3
arr = np.zeros((n,n))
print(np.random.choice(range(n*n),p,replace = False))
np.put(arr,np.random.choice(range(n*n),p,replace = False),1)
print(arr)

[23 19  1]
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [94]:
x = np.random.rand(5,10)
y = x - x.mean(axis=1,keepdims=True)
print(x)
print(y)

[[0.62285444 0.57037803 0.45590338 0.46071968 0.24503736 0.83356879
  0.78813716 0.64511179 0.65757781 0.51748029]
 [0.453384   0.57241757 0.29473809 0.4152192  0.28836643 0.1238224
  0.11775115 0.0661539  0.91854274 0.35517922]
 [0.1693327  0.05377036 0.81004046 0.43895854 0.54566114 0.97485228
  0.14656599 0.11821139 0.80239324 0.41046858]
 [0.46675673 0.34859502 0.98168542 0.25139742 0.52096286 0.43755775
  0.76129241 0.17297749 0.67578992 0.36547358]
 [0.13216411 0.62629866 0.77264948 0.288062   0.92663787 0.99833874
  0.95775613 0.10413081 0.44919226 0.43857374]]
[[ 0.04317757 -0.00929884 -0.1237735  -0.11895719 -0.33463951  0.25389191
   0.20846029  0.06543491  0.07790094 -0.06219658]
 [ 0.09282653  0.2118601  -0.06581938  0.05466172 -0.07219104 -0.23673507
  -0.24280632 -0.29440357  0.55798527 -0.00537825]
 [-0.27769277 -0.39325511  0.36301499 -0.00806693  0.09863567  0.52782681
  -0.30045948 -0.32881407  0.35536778 -0.03655689]
 [-0.03149213 -0.14965384  0.48343655 -0.24685144 

#### 59. How to sort an array by the nth column? (★★☆)

In [95]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 0 4]
 [3 2 4]
 [1 4 9]]
[[6 0 4]
 [3 2 4]
 [1 4 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [96]:
arr = np.random.randint(0,3,(3,10))
print(arr)
print(~arr.any(axis=0))
print((~arr.any(axis=0)).any())

[[0 1 0 0 0 1 1 0 0 0]
 [0 1 2 2 0 0 0 1 1 0]
 [0 0 0 0 2 1 0 0 2 1]]
[ True False False False False False False False False False]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [97]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4342952899695366


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [98]:
import numpy as np

In [99]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [100]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z)

[0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [101]:
Z= np.ones(10)
I = np.random.randint(0,len(Z),20)                   
Z += np.bincount(I, minlength=len(Z))                #method1 using np.bincount
print(Z)
unique,count = np.unique(I,return_counts = True)     #method2 using np.unique
# print(np.asarray((unique,count)))
print(count+1)

[3. 1. 5. 5. 4. 4. 1. 1. 2. 4.]
[3 5 5 4 4 2 4]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [102]:
X = [1,2,3,4,5,6]
I = np.arange(6)
F = np.bincount(I,X)       #elements of X acts as weights
print(F)

[1. 2. 3. 4. 5. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [103]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
# print(I[...,1])
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
# print(F[...])
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [104]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
# print(A.shape[:-2] + (-1,))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)
# print(A.reshape(A.shape[:-2] + (-1,)))

[[61 78 56 53]
 [46 53 61 56]
 [52 44 44 64]]
[[61 78 56 53]
 [46 53 61 56]
 [52 44 44 64]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [105]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.7225549  0.49153322 0.4888452  0.4928489  0.43785753 0.35149381
 0.58061718 0.40611188 0.45420969 0.46938358]
0    0.722555
1    0.491533
2    0.488845
3    0.492849
4    0.437858
5    0.351494
6    0.580617
7    0.406112
8    0.454210
9    0.469384
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [106]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
print(np.diag(np.dot(A, B)))

# Fast version
print(np.sum(A * B.T, axis=1))

# Faster version
print(np.einsum("ij,ji->i", A, B))

[1.60538871 1.09117179 1.58457191 1.09781506 0.16905325]
[1.60538871 1.09117179 1.58457191 1.09781506 0.16905325]
[1.60538871 1.09117179 1.58457191 1.09781506 0.16905325]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [107]:
arr = np.array([1,2,3,4,5])
shift = 3
ans = np.zeros(len(arr)+(len(arr)-1)*shift)
ans[::shift+1]=arr
print(ans)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [108]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [109]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)